apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring_demo
spec:
  selector:
    matchLabels:
      app: spring_demo
  replicas: 2
  template:
    metadata:
      labels:
        app: spring_demo
    spec:
      containers:
        - name: spring_demo
          image: spring_demo-1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083