apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod1
  labels:
    team: integrations
spec:
  containers:
    - name: mongo-container
      image: mongo:latest
      ports:
        - containerPort: 27017