apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-simpleapp
spec:
  schedule: "*/1 * * * *" #every 1 min
  jobTemplate:
   spec:
    template:
      spec:
        containers:
        - name: simpleapp-container
          image: simpleapp
          imagePullPolicy: IfNotPresent
      
        restartPolicy: OnFailure
